name: CD

on:
  workflow_dispatch:

jobs:
  publish:
    environment: NuGet
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # Run GenerateSolution.ps1
      - name: Run GenerateSolution.ps1
        shell: pwsh
        run: .\GenerateSolution.ps1

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/Riverside.Win32.sln

      # Build the solution
      - name: Build solution
        run: dotnet build src/Riverside.Win32.sln --configuration Release -p:ContinuousIntegrationBuild=true

      # Pack the solution
      - name: Pack solution
        run: dotnet pack src/Riverside.Win32.sln --configuration Release --output ./output

      # Publish to NuGet
      - name: Publish to NuGet
        run: dotnet nuget push .\output\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
